# Generated by Django 4.0.4 on 2022-08-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='partss', to='product.brands'),
        ),
    ]
